/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as TestManualSearchRouteImport } from './routes/test/manual-search'
import { Route as SettingsStatusRouteImport } from './routes/settings/status'
import { Route as SettingsScannerRouteImport } from './routes/settings/scanner'
import { Route as SettingsQbittorrentRouteImport } from './routes/settings/qbittorrent'
import { Route as SettingsPerformanceRouteImport } from './routes/settings/performance'
import { Route as SettingsLogsRouteImport } from './routes/settings/logs'
import { Route as SettingsHomepageRouteImport } from './routes/settings/homepage'
import { Route as SettingsExportRouteImport } from './routes/settings/export'
import { Route as SettingsConnectionRouteImport } from './routes/settings/connection'
import { Route as SettingsCacheRouteImport } from './routes/settings/cache'
import { Route as SettingsBackupRouteImport } from './routes/settings/backup'
import { Route as MediaTypeIdRouteImport } from './routes/media/$type.$id'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const TestManualSearchRoute = TestManualSearchRouteImport.update({
  id: '/test/manual-search',
  path: '/test/manual-search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsStatusRoute = SettingsStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsScannerRoute = SettingsScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsQbittorrentRoute = SettingsQbittorrentRouteImport.update({
  id: '/qbittorrent',
  path: '/qbittorrent',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPerformanceRoute = SettingsPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLogsRoute = SettingsLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsHomepageRoute = SettingsHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsExportRoute = SettingsExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionRoute = SettingsConnectionRouteImport.update({
  id: '/connection',
  path: '/connection',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCacheRoute = SettingsCacheRouteImport.update({
  id: '/cache',
  path: '/cache',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBackupRoute = SettingsBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => SettingsRoute,
} as any)
const MediaTypeIdRoute = MediaTypeIdRouteImport.update({
  id: '/media/$type/$id',
  path: '/media/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/library': typeof LibraryRoute
  '/pending': typeof PendingRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/settings/cache': typeof SettingsCacheRoute
  '/settings/connection': typeof SettingsConnectionRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/homepage': typeof SettingsHomepageRoute
  '/settings/logs': typeof SettingsLogsRoute
  '/settings/performance': typeof SettingsPerformanceRoute
  '/settings/qbittorrent': typeof SettingsQbittorrentRoute
  '/settings/scanner': typeof SettingsScannerRoute
  '/settings/status': typeof SettingsStatusRoute
  '/test/manual-search': typeof TestManualSearchRoute
  '/settings/': typeof SettingsIndexRoute
  '/media/$type/$id': typeof MediaTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/library': typeof LibraryRoute
  '/pending': typeof PendingRoute
  '/search': typeof SearchRoute
  '/setup': typeof SetupRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/settings/cache': typeof SettingsCacheRoute
  '/settings/connection': typeof SettingsConnectionRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/homepage': typeof SettingsHomepageRoute
  '/settings/logs': typeof SettingsLogsRoute
  '/settings/performance': typeof SettingsPerformanceRoute
  '/settings/qbittorrent': typeof SettingsQbittorrentRoute
  '/settings/scanner': typeof SettingsScannerRoute
  '/settings/status': typeof SettingsStatusRoute
  '/test/manual-search': typeof TestManualSearchRoute
  '/settings': typeof SettingsIndexRoute
  '/media/$type/$id': typeof MediaTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/library': typeof LibraryRoute
  '/pending': typeof PendingRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/settings/cache': typeof SettingsCacheRoute
  '/settings/connection': typeof SettingsConnectionRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/homepage': typeof SettingsHomepageRoute
  '/settings/logs': typeof SettingsLogsRoute
  '/settings/performance': typeof SettingsPerformanceRoute
  '/settings/qbittorrent': typeof SettingsQbittorrentRoute
  '/settings/scanner': typeof SettingsScannerRoute
  '/settings/status': typeof SettingsStatusRoute
  '/test/manual-search': typeof TestManualSearchRoute
  '/settings/': typeof SettingsIndexRoute
  '/media/$type/$id': typeof MediaTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/downloads'
    | '/library'
    | '/pending'
    | '/search'
    | '/settings'
    | '/setup'
    | '/settings/backup'
    | '/settings/cache'
    | '/settings/connection'
    | '/settings/export'
    | '/settings/homepage'
    | '/settings/logs'
    | '/settings/performance'
    | '/settings/qbittorrent'
    | '/settings/scanner'
    | '/settings/status'
    | '/test/manual-search'
    | '/settings/'
    | '/media/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/downloads'
    | '/library'
    | '/pending'
    | '/search'
    | '/setup'
    | '/settings/backup'
    | '/settings/cache'
    | '/settings/connection'
    | '/settings/export'
    | '/settings/homepage'
    | '/settings/logs'
    | '/settings/performance'
    | '/settings/qbittorrent'
    | '/settings/scanner'
    | '/settings/status'
    | '/test/manual-search'
    | '/settings'
    | '/media/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/downloads'
    | '/library'
    | '/pending'
    | '/search'
    | '/settings'
    | '/setup'
    | '/settings/backup'
    | '/settings/cache'
    | '/settings/connection'
    | '/settings/export'
    | '/settings/homepage'
    | '/settings/logs'
    | '/settings/performance'
    | '/settings/qbittorrent'
    | '/settings/scanner'
    | '/settings/status'
    | '/test/manual-search'
    | '/settings/'
    | '/media/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadsRoute: typeof DownloadsRoute
  LibraryRoute: typeof LibraryRoute
  PendingRoute: typeof PendingRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SetupRoute: typeof SetupRoute
  TestManualSearchRoute: typeof TestManualSearchRoute
  MediaTypeIdRoute: typeof MediaTypeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/test/manual-search': {
      id: '/test/manual-search'
      path: '/test/manual-search'
      fullPath: '/test/manual-search'
      preLoaderRoute: typeof TestManualSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/status': {
      id: '/settings/status'
      path: '/status'
      fullPath: '/settings/status'
      preLoaderRoute: typeof SettingsStatusRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/scanner': {
      id: '/settings/scanner'
      path: '/scanner'
      fullPath: '/settings/scanner'
      preLoaderRoute: typeof SettingsScannerRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/qbittorrent': {
      id: '/settings/qbittorrent'
      path: '/qbittorrent'
      fullPath: '/settings/qbittorrent'
      preLoaderRoute: typeof SettingsQbittorrentRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/performance': {
      id: '/settings/performance'
      path: '/performance'
      fullPath: '/settings/performance'
      preLoaderRoute: typeof SettingsPerformanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/logs': {
      id: '/settings/logs'
      path: '/logs'
      fullPath: '/settings/logs'
      preLoaderRoute: typeof SettingsLogsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/homepage': {
      id: '/settings/homepage'
      path: '/homepage'
      fullPath: '/settings/homepage'
      preLoaderRoute: typeof SettingsHomepageRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/export': {
      id: '/settings/export'
      path: '/export'
      fullPath: '/settings/export'
      preLoaderRoute: typeof SettingsExportRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connection': {
      id: '/settings/connection'
      path: '/connection'
      fullPath: '/settings/connection'
      preLoaderRoute: typeof SettingsConnectionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/cache': {
      id: '/settings/cache'
      path: '/cache'
      fullPath: '/settings/cache'
      preLoaderRoute: typeof SettingsCacheRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/backup': {
      id: '/settings/backup'
      path: '/backup'
      fullPath: '/settings/backup'
      preLoaderRoute: typeof SettingsBackupRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/media/$type/$id': {
      id: '/media/$type/$id'
      path: '/media/$type/$id'
      fullPath: '/media/$type/$id'
      preLoaderRoute: typeof MediaTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsBackupRoute: typeof SettingsBackupRoute
  SettingsCacheRoute: typeof SettingsCacheRoute
  SettingsConnectionRoute: typeof SettingsConnectionRoute
  SettingsExportRoute: typeof SettingsExportRoute
  SettingsHomepageRoute: typeof SettingsHomepageRoute
  SettingsLogsRoute: typeof SettingsLogsRoute
  SettingsPerformanceRoute: typeof SettingsPerformanceRoute
  SettingsQbittorrentRoute: typeof SettingsQbittorrentRoute
  SettingsScannerRoute: typeof SettingsScannerRoute
  SettingsStatusRoute: typeof SettingsStatusRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsBackupRoute: SettingsBackupRoute,
  SettingsCacheRoute: SettingsCacheRoute,
  SettingsConnectionRoute: SettingsConnectionRoute,
  SettingsExportRoute: SettingsExportRoute,
  SettingsHomepageRoute: SettingsHomepageRoute,
  SettingsLogsRoute: SettingsLogsRoute,
  SettingsPerformanceRoute: SettingsPerformanceRoute,
  SettingsQbittorrentRoute: SettingsQbittorrentRoute,
  SettingsScannerRoute: SettingsScannerRoute,
  SettingsStatusRoute: SettingsStatusRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadsRoute: DownloadsRoute,
  LibraryRoute: LibraryRoute,
  PendingRoute: PendingRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SetupRoute: SetupRoute,
  TestManualSearchRoute: TestManualSearchRoute,
  MediaTypeIdRoute: MediaTypeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
